#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# generate_audio.sh  —  Run this ONCE on your Mac to create speech C arrays
# Uses macOS built-in `say` + `afconvert` (no install needed)
# Compatible with macOS default bash 3.2 (no declare -A)
# Output: src/audio_data.h  (12 spoken words as PCM arrays for ESP32 I2S)
# ─────────────────────────────────────────────────────────────────────────────

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TMP_DIR="$SCRIPT_DIR/.audio_tmp"
OUT_H="$SCRIPT_DIR/src/audio_data.h"

mkdir -p "$TMP_DIR"

# Words in order (name == spoken text, so no associative array needed)
WORDS="hi one two three four five six seven eight nine ten bye"

echo "Generating speech audio with macOS 'say'..."

for name in $WORDS; do
  aiff="$TMP_DIR/$name.aiff"
  wav="$TMP_DIR/$name.wav"
  # macOS TTS → AIFF, then convert: 48kHz / 16-bit / mono / little-endian
  say -v Samantha -r 150 "$name" -o "$aiff"
  afconvert -f WAVE -d LEI16@48000 -c 1 "$aiff" "$wav"
  echo "  ✓ $name"
done

echo "Converting WAVs to C arrays..."

python3 - "$TMP_DIR" "$OUT_H" $WORDS << 'PYEOF'
import sys, struct, wave, os

tmp_dir = sys.argv[1]
out_h   = sys.argv[2]
names   = sys.argv[3:]

lines = []
lines.append("// AUTO-GENERATED by generate_audio.sh — do not edit by hand")
lines.append("// 48 kHz, 16-bit, mono PCM arrays for ESP32 I2S playback")
lines.append("#pragma once")
lines.append("#include <stdint.h>")
lines.append("#include <stddef.h>")
lines.append("")

for name in names:
    wav_path = os.path.join(tmp_dir, f"{name}.wav")
    with wave.open(wav_path, "rb") as wf:
        assert wf.getsampwidth() == 2, "Need 16-bit"
        assert wf.getnchannels() == 1, "Need mono"
        assert wf.getframerate() == 48000, "Need 48kHz"
        raw = wf.readframes(wf.getnframes())

    samples = struct.unpack(f"<{len(raw)//2}h", raw)
    # Reduce volume by 50% to avoid clipping through small speaker
    samples = [max(-32768, min(32767, s // 2)) for s in samples]

    sym = f"audio_{name}"
    lines.append(f"// '{name}' — {len(samples)} samples ({len(samples)/48000:.2f}s)")
    lines.append(f"static const int16_t {sym}[] = {{")

    row = []
    for i, s in enumerate(samples):
        row.append(f"{s:6d}")
        if len(row) == 16 or i == len(samples)-1:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    lines.append(f"static const size_t {sym}_len = {len(samples)};")
    lines.append("")

# Table for easy lookup
lines.append("typedef struct { const int16_t *samples; size_t len; } AudioClip;")
lines.append("")
lines.append("static const AudioClip AUDIO_CLIPS[] = {")
for name in names:
    lines.append(f"    {{ audio_{name}, audio_{name}_len }},  // {name}")
lines.append("};")
lines.append(f"#define AUDIO_CLIP_COUNT {len(names)}")
lines.append("")

with open(out_h, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"Written: {out_h}")
PYEOF

rm -rf "$TMP_DIR"
echo ""
echo "✅  Done!  src/audio_data.h is ready."
echo "    Now build & flash with: pio run --target upload"
