#!/bin/bash
# =============================================================================
# generate_audio.sh — Gestura speech audio generator
# =============================================================================
# TO ADD A NEW CLIP: just add a line to the CLIPS section below, then run:
#   ./generate_audio.sh && pio run --target upload
#
# FORMAT (one clip per line, fields separated by |):
#   name | spoken text | voice | rate (wpm)
#
# Common macOS voices: Samantha (female), Alex (male), Daniel (British male)
#   Tom (male), Victoria (female), Karen (Australian female)
#
# Outputs: src/audio_all.h  — single file with all clips + lookup table
# =============================================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TMP_DIR="$SCRIPT_DIR/.audio_tmp"
OUT_H="$SCRIPT_DIR/src/audio_all.h"

mkdir -p "$TMP_DIR"

# =============================================================================
# ▼▼▼  ADD NEW CLIPS HERE — one line per clip  ▼▼▼
# =============================================================================
CLIPS="
letter_a    | a           | Samantha | 150
letter_b    | b           | Samantha | 150
letter_c    | c           | Samantha | 150
letter_d    | d           | Samantha | 150
letter_e    | e           | Samantha | 150
letter_f    | f           | Samantha | 150
letter_g    | g           | Samantha | 150
letter_h    | h           | Samantha | 150
letter_i    | i           | Samantha | 150
letter_j    | j           | Samantha | 150
letter_k    | k           | Samantha | 150
letter_l    | l           | Samantha | 150
letter_m    | m           | Samantha | 150
letter_n    | n           | Samantha | 150
letter_o    | o           | Samantha | 150
letter_p    | p           | Samantha | 150
letter_q    | q           | Samantha | 150
letter_r    | r           | Samantha | 150
letter_s    | s           | Samantha | 150
letter_t    | t           | Samantha | 150
letter_u    | u           | Samantha | 150
letter_v    | v           | Samantha | 150
letter_w    | w           | Samantha | 150
letter_x    | x           | Samantha | 150
letter_y    | y           | Samantha | 150
letter_z    | z           | Samantha | 150
i_love_you  | I love you  | Samantha | 85
fuck_you    | Fuck you    | Alex     | 130
"
# =============================================================================
# ▲▲▲  END OF CLIP LIST  ▲▲▲
# =============================================================================

echo "Generating audio clips..."

# Parse CLIPS and generate WAVs
while IFS='|' read -r name text voice rate; do
  # Skip blank lines
  name=$(echo "$name" | tr -d ' \t')
  [ -z "$name" ] && continue

  text=$(echo "$text"   | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
  voice=$(echo "$voice" | tr -d ' \t')
  rate=$(echo "$rate"   | tr -d ' \t')

  aiff="$TMP_DIR/$name.aiff"
  wav="$TMP_DIR/$name.wav"

  say -v "$voice" -r "$rate" "$text" -o "$aiff"
  afconvert -f WAVE -d LEI16@48000 -c 1 "$aiff" "$wav"
  echo "  ✓ $name  (\"$text\", $voice, ${rate}wpm)"
done << CLIPS_EOF
$CLIPS
CLIPS_EOF

echo ""
echo "Building src/audio_all.h..."

# Collect all generated WAV stems (in order)
STEMS=""
while IFS='|' read -r name text voice rate; do
  name=$(echo "$name" | tr -d ' \t')
  [ -z "$name" ] && continue
  STEMS="$STEMS $name"
done << CLIPS_EOF
$CLIPS
CLIPS_EOF

python3 - "$TMP_DIR" "$OUT_H" $STEMS << 'PYEOF'
import sys, struct, wave, os

SAMPLE_RATE = 48000

tmp_dir = sys.argv[1]
out_h   = sys.argv[2]
names   = sys.argv[3:]

lines = []
lines.append("// AUTO-GENERATED by generate_audio.sh — do not edit by hand")
lines.append("// To add clips: edit generate_audio.sh and re-run it")
lines.append("// 48 kHz, 16-bit, mono PCM with silence trimming")
lines.append("#pragma once")
lines.append("#include <stdint.h>")
lines.append("#include <stddef.h>")
lines.append("#include <string.h>")
lines.append("")

# Raw PCM arrays
for name in names:
    wav_path = os.path.join(tmp_dir, f"{name}.wav")
    with wave.open(wav_path, "rb") as wf:
        assert wf.getsampwidth() == 2
        assert wf.getnchannels() == 1
        assert wf.getframerate() == SAMPLE_RATE
        raw = wf.readframes(wf.getnframes())

    samples = list(struct.unpack(f"<{len(raw)//2}h", raw))

    # Trim silence
    threshold = 328
    start = 0
    while start < len(samples) and abs(samples[start]) < threshold:
        start += 1
    end = len(samples) - 1
    while end > start and abs(samples[end]) < threshold:
        end -= 1
    pad = 480
    start = max(0, start - pad)
    end = min(len(samples) - 1, end + pad)
    samples = samples[start:end + 1]

    sym = f"_audio_{name}"
    lines.append(f"// '{name}'  {len(samples)} samples  ({len(samples)/SAMPLE_RATE:.2f}s)")
    lines.append(f"static const int16_t {sym}[] = {{")
    row = []
    for i, s in enumerate(samples):
        row.append(f"{s:6d}")
        if len(row) == 16 or i == len(samples) - 1:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    lines.append("")

# Named lookup table
lines.append("// ── Named clip lookup table ────────────────────────────────")
lines.append("typedef struct {")
lines.append("    const char    *name;")
lines.append("    const int16_t *samples;")
lines.append("    size_t         len;")
lines.append("} SpeechClip;")
lines.append("")
lines.append("static const SpeechClip _ALL_CLIPS[] = {")
for name in names:
    lines.append(f'    {{ "{name}", _audio_{name}, sizeof(_audio_{name})/sizeof(int16_t) }},')
lines.append("};")
lines.append(f"#define SPEECH_CLIP_COUNT  {len(names)}")
lines.append("")

# Lookup + play function declarations (implementation in speech.h)
lines.append("// ── Lookup by name (returns NULL if not found) ─────────────")
lines.append("static inline const SpeechClip *speech_find(const char *name) {")
lines.append("    for (int i = 0; i < SPEECH_CLIP_COUNT; i++)")
lines.append('        if (strcmp(_ALL_CLIPS[i].name, name) == 0)')
lines.append("            return &_ALL_CLIPS[i];")
lines.append("    return (void*)0;")
lines.append("}")
lines.append("")

with open(out_h, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"  → {out_h}  ({len(names)} clips)")
PYEOF

rm -rf "$TMP_DIR"

echo ""
echo "✅  Done!  src/audio_all.h has all clips."
echo ""
echo "    Usage in your code:"
echo "      speech_play(\"i_love_you\");"
echo "      speech_play(\"letter_a\");"
echo ""
echo "    Build & flash:  pio run --target upload"
